name: pubversion
description: A package to easily increment version numbers in pubspec.yaml files.
version: 1.1.0
homepage: https://megamattmiller.github.io/pubversion/
repository: https://github.com/MegaMattMiller/pubversion

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  path: ^1.6.2
  pubspec_parse: ^0.1.4
  pub_semver: ^1.4.2
  args: ^1.5.2
  io: ^0.3.3

dev_dependencies:
  pedantic: ^1.9.0

executables:
  pubversion:
