name: pubversion
description: A package to easily increment version numbers in pubspec.yaml files.
version: 1.0.0-rc.2
authors:
- Matt miller <matt@mattmiller.dev>
homepage: https://github.com/MegaMattMiller/pubversion

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  path: ^1.5.1
  pubspec_parse: ^0.1.4
  pub_semver: ^1.3.2
  args: ^1.5.2
  io: ^0.3.2+1

executables:
  pubversion: